services:
  ros:
    build: .
    image: robotics:ros
    container_name: robotics-ros
    user: docker:docker
    group_add:
      - audio
      - dialout
      - sudo
      - video
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/docker/ws/src
    tmpfs:
      - /tmp
    tty: true
    stdin_open: true
    network_mode: host
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    privileged: true
