footprint: [[-0.306, -0.29], [-0.306, 0.29], [0.306, 0.29], [0.306, -0.29]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 0.2

resolution: 0.05

static:
  map_topic: map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: hokuyo/scan, inf_is_valid: true}

inflation:
  inflation_radius: 0.5
