planner_frequency: 2.0
controller_frequency: 10.0

recovery_behaviour_enabled: true

GlobalPlanner:
  allow_unknown: true
  default_tolerance: 0.2

DWAPlannerROS:
  acc_lim_x: 1.0
  acc_lim_y: 0
  acc_lim_th: 1.0

  max_vel_trans: 0.3
  min_vel_trans: 0.1
  max_vel_rot: 0.5
  min_vel_rot: 0.2

  max_vel_x: 0.3
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false
